<a href="https://colab.research.google.com/github/Arabinda768228/Data_preprocessing/blob/main/Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing | Machine Learning Bootcamp

## Import the required libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import the dataset

In [ ]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values


In [ ]:
print(X)

[['India' 44.0 72000.0]
 ['Thailand ' 27.0 48000.0]
 ['Indonesia' 30.0 54000.0]
 ['China' 38.0 61000.0]
 ['India' 40.0 nan]
 ['China' 35.0 58000.0]
 ['Thailand ' nan 52000.0]
 ['India' 48.0 79000.0]
 ['Indonesia' 50.0 83000.0]
 ['Thailand ' 37.0 67000.0]
 ['India' 25.0 nan]
 ['Thailand ' 36.0 60000.0]
 ['Indonesia' 42.0 64000.0]
 ['India' nan 40000.0]
 ['Thailand ' 52.0 90000.0]
 ['Indonesia' nan 55000.0]
 ['China' 41.0 nan]
 ['India' 29.0 48000.0]
 ['China' 43.0 70000.0]]


In [ ]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes'
 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Solving for missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
print(X)

[['India' 44.0 72000.0]
 ['Thailand ' 27.0 48000.0]
 ['Indonesia' 30.0 54000.0]
 ['China' 38.0 61000.0]
 ['India' 40.0 62562.5]
 ['China' 35.0 58000.0]
 ['Thailand ' 38.5625 52000.0]
 ['India' 48.0 79000.0]
 ['Indonesia' 50.0 83000.0]
 ['Thailand ' 37.0 67000.0]
 ['India' 25.0 62562.5]
 ['Thailand ' 36.0 60000.0]
 ['Indonesia' 42.0 64000.0]
 ['India' 38.5625 40000.0]
 ['Thailand ' 52.0 90000.0]
 ['Indonesia' 38.5625 55000.0]
 ['China' 41.0 62562.5]
 ['India' 29.0 48000.0]
 ['China' 43.0 70000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

Column_transform = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])],
                                     remainder = 'passthrough')
X = np.array(Column_transform.fit_transform(X))

In [ ]:
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 40.0 62562.5]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 38.5625 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 1.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 25.0 62562.5]
 [0.0 0.0 0.0 1.0 36.0 60000.0]
 [0.0 0.0 1.0 0.0 42.0 64000.0]
 [0.0 1.0 0.0 0.0 38.5625 40000.0]
 [0.0 0.0 0.0 1.0 52.0 90000.0]
 [0.0 0.0 1.0 0.0 38.5625 55000.0]
 [1.0 0.0 0.0 0.0 41.0 62562.5]
 [0.0 1.0 0.0 0.0 29.0 48000.0]
 [1.0 0.0 0.0 0.0 43.0 70000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [ ]:
print(Y)

[0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2,random_state = 40)

In [ ]:
print(X_train)

[[0.0 0.0 1.0 0.0 42.0 64000.0]
 [1.0 0.0 0.0 0.0 43.0 70000.0]
 [0.0 0.0 0.0 1.0 52.0 90000.0]
 [0.0 0.0 0.0 1.0 37.0 67000.0]
 [0.0 0.0 0.0 1.0 36.0 60000.0]
 [1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 38.5625 40000.0]
 [0.0 1.0 0.0 0.0 29.0 48000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 0.0 38.5625 55000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 1.0 38.5625 52000.0]]


In [ ]:
print(X_test)

[[1.0 0.0 0.0 0.0 41.0 62562.5]
 [0.0 1.0 0.0 0.0 25.0 62562.5]
 [0.0 1.0 0.0 0.0 40.0 62562.5]
 [0.0 1.0 0.0 0.0 44.0 72000.0]]


In [ ]:
print(Y_train)

[1 1 1 1 0 0 1 0 1 0 0 0 1 1 0]


In [ ]:
print(Y_test)

[1 0 1 0]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.fit_transform(X_test)

In [ ]:
print(X_train)

[[-0.5        -0.5         1.6583124  -0.70710678  0.44570485  0.15355946]
 [ 2.         -0.5        -0.60302269 -0.70710678  0.58701154  0.59937724]
 [-0.5        -0.5        -0.60302269  1.41421356  1.85877174  2.08543652]
 [-0.5        -0.5        -0.60302269  1.41421356 -0.2608286   0.37646835]
 [-0.5        -0.5        -0.60302269  1.41421356 -0.40213529 -0.1436524 ]
 [ 2.         -0.5        -0.60302269 -0.70710678 -0.11952191 -0.06934943]
 [-0.5         2.         -0.60302269 -0.70710678 -0.0400369  -1.62971168]
 [-0.5         2.         -0.60302269 -0.70710678 -1.39128211 -1.03528797]
 [-0.5        -0.5        -0.60302269  1.41421356 -1.67389549 -1.03528797]
 [-0.5        -0.5         1.6583124  -0.70710678 -1.24997542 -0.58947018]
 [-0.5        -0.5         1.6583124  -0.70710678 -0.0400369  -0.51516722]
 [-0.5        -0.5         1.6583124  -0.70710678  1.57615836  1.56531578]
 [ 2.         -0.5        -0.60302269 -0.70710678 -0.54344198 -0.29225833]
 [-0.5         2.        

In [ ]:
print(X_test)

[[ 1.73205081 -1.73205081  0.          0.          0.47519096 -0.57735027]
 [-0.57735027  0.57735027  0.          0.         -1.69711058 -0.57735027]
 [-0.57735027  0.57735027  0.          0.          0.33942212 -0.57735027]
 [-0.57735027  0.57735027  0.          0.          0.8824975   1.73205081]]
